### ISSUE TITLE
Undefined functions or variables in `mysql/storage/ermia/ha_ermia.cc`

### ISSUE THREAD

**Issue by gcc17** [sfu-dis/skeena#2]
Dear authors, 

I really appreciate your efforts in the open-source implementation!
I came across some issues in the compilation of `mysql/storage/ermia/ha_ermia.cc`, after I built `ermia`, customized the paths in `mysql/ermia-contrib/BUILD` and run make. 

1. It first said that `class "ermia::ConcurrentMasstreeIndex" has no member "GetRecordMultiIt"`, and a suggested substitute was the `GetRecordMulti` function in `ermia.h`. So I changed the `rc = idx->GetRecordMultiIt(et->tx, *key, &et->dir_it);` at line 800 of `ha_ermia.cc` to `idx->GetRecordMulti(et->tx, rc, *key, &et->dir_it);`, and it worked. It appears that the function declaration had changed. 

2. Then at line 232, it reported error of `no template named 'ScanIterator' in 'ermia::mbtree<ermia::masstree_params>'
  ermia::ConcurrentMasstree::ScanIterator<false> *scan_iter = nullptr;`. The `ConcurrentMasstree` is defined as `mbtree<masstree_params>` in `skeena/ermia/masstree/masstree_btree.h`. But there is no variable named as `ScanIterator` in `mbtree`. Besides, at line 816, it seems that `ScanIterator` has a member function called `session_factory`, but it cannot be found, either. 

3. At line 233, it is claimed that `ermia::DirIterator dir_it;`. But the error output said that namespace "ermia" has no member "DirIterator".

I wonder whether the `ermia` directory in this repo have some missing files which are not uploaded here. Thanks a lot for your help!

**Comment by KaisongHuang** [comment]
Hi there,

We are looking into the issue. Thank you for letting us know.

**Comment by KaisongHuang** [comment]
We have resolved the issue in PR #3.
